config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  get 'homes/index'
  get 'top' => 'homes#top'

  root 'homes#top'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :users do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  resources :users do
    collection do
      get :profile
    end

    collection do
      get :show2
    end
  end

  resources :rooms do
    collection do
      get :search
    end
  end
  resources :reservations do
    collection do
      get :complete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  def amount_days
    self.total_days = (self.checkout_date - self.check_in_date).to_i
  end

  def amount_price
    total_price = room.price * self.guests_count.to_i * total_days

  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @user = current_user
    @reservations = current_user.reservations
  end

  def new
    @user = current_user
    @reservation = Reservation.new(reservation_params)
    @room = Room.find(params[:room_id])
    @reservation.room = @room
    if @reservation.checkout_date.nil?
      flash.now[:alert] = "日付を指定ください"
      render 'rooms/show'
    elsif @reservation.guests_count.nil?
      flash.now[:alert] = "予約人数を入力してください"
      render 'rooms/show'
    elsif @reservation.checkout_date < @reservation.check_in_date
      flash.now[:alert] = "開始日より後の日付をを入力してください"
      render 'rooms/show'
    else
      @reservation.total_days = @reservation.amount_days
      @reservation.total_amount = @reservation.amount_price
    end

  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    @room = Room.find(params[:reservation][:room_id])
    @reservation.room = @room
    @reservation.save!
    render "complete"
  end

  def complete
  end


  private

  def reservation_params
    params.permit(:check_in_date, :checkout_date, :guests_count)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/complete.html.erb
<div class="complete">
  <h2>予約完了!</h2>
    <p class="complete">ご予約ありがとうございました。</p>

      <div class="return_top_btn">
        <%= link_to "トップページに戻る", homes_top_path, class:"return_top" %>
      </div>
</div>

app/views/reservations/index.html.erb
<div class="main_container">
  <div class="information">
    <h3>予約済みルーム一覧</h3>
   </div>

<table>
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>合計料金</th>
      <th>予約確定日</th>
    </tr>
  </thead>
  <tbody>

  </tbody>
     <% @reservations.each do |reservation| %>
       <tr>
          <td>
            <% if reservation.room.img.attached? %>
              <%= image_tag reservation.room.img ,class:"room-icon"%>
            <% end %>
          </td>
          <td><%= reservation.room.name %></td>
          <td><%= reservation.room.description %></td>
          <td><%=reservation.room.price %></td>
          <td><%= reservation.room.created_at.to_s(:datetime_jp) %></td>
        </tr>
      <% end %>

    </tbody>
  </table>

app/views/reservations/new.html.erb
<div class="confirm_box">
  <h2>予約確認画面</h2>

   <h2 class="3price_day">￥<%= @room.price %>/日</h2>

   <ul>
     <li>チェックイン</li>
     <li class="info"><%= @reservation.check_in_date  %></li>
     
     <li>チェクアウト</li>
     <li class="info"><%= @reservation.checkout_date  %></li>

     <li>使用日数</li>
     <li class="info"><%= @reservation.total_days %></li>

     <li>人数</li>
     <li class="info"><%= @reservation.guests_count %></li>

     <li>合計金額</li>
     <li class="info"><%= @reservation.total_amount %></li>
   </ul>
</div>

<p class="kakutei">上記内容でよろしければ予約確定を押してください</p>

<%= form_with model: @reservation, url: reservations_path do |r| %>
<%= r.hidden_field :check_in_date ,value:@reservation.check_in_date %>
<%= r.hidden_field :checkout_dake,value:@reservation.checkout_date %>
<%= r.hidden_field :guests_count,value:@reservation.total_days %>
<%= r.hidden_field :total_days,value:@reservation.guests_count %>
<%= r.hidden_field :total_days,value:@reservation.total_amount %>
<%= r.hidden_field :room_id,value: @reservation.room_id %>

<p><%= r.submit "予約を確定する",id:"submit_new_reserve" %></p>
<p class="return_reserve_bottom"><%= link_to "予約画面に戻る", :rooms ,id:"return_reserve" %></p>
<% end %>