config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  get 'homes/index'
  get 'top' => 'homes#top'

  root 'homes#top'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :users do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  resources :users do
    collection do
      get :profile
    end

    collection do
      get :show2
    end
  end

  resources :rooms do
    collection do
      get :search
    end
  end
  resources :reservations do
    collection do
      get :complete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations
  belongs_to :user

  has_one_attached :img

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true


  def self.search(search)
    if search
      Room.where(['name LIKE ? OR address LIKE ? OR description LIKE ? ', "%#{search}%", "%#{search}%", "%#{search}%"])
		else
		  Room.all
		end
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
    @user = current_user
  end

  def create
    @room = Room.new(params.require(:room).permit(:name,:description,:address,:price,:img))
    @room.user_id = current_user.id
    @user = current_user
    if @room.save
      redirect_to :rooms
      flash[:notice] = "部屋の登録が完了しました"
    else
      render "new"
    end
  end

  def show
    @user = current_user
    @room = Room.find(params[:id])
  end

  def search
    @user = current_user
    @rooms = Room.search(params[:search])
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to :rooms
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class ="reserve_index">
  <div class="information">
    <h3>登録したルーム一覧</h3>
  </div>

  <table>
    <thead>
      <tr>

        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
        <th>削除</th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td>
            <% if room.img.attached? %>
              <%= image_tag room.img ,class:"room-icon"%>
            <% end %>
          </td>
          <td><%= link_to room.name , room,class:"name_link" %></td>
          <td><%= room.description %></td>
          <td><%= room.price %></td>
          <td><%= room.created_at.to_s(:datetime_jp) %></td>
          <td><%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } %>
        </tr>
      <% end %>

      
      </tbody>
   </table>
</div>

app/views/rooms/new.html.erb
<div class="room_page">
  <div class="room_main">
   <%= form_with model: @room do |f| %>
    <table class="room-register">
      <tr>
        <th><%= f.label :ルーム名, class: "label" %></th>
        <td><%= f.text_field :name,  placeholder: "ルーム名入力", autofocus: true, autocomplete: "name",  class: "input" %></td>
      </tr>
      <tr>
        <th><%= f.label :ルーム紹介, class: "label" %></th>
        <td><%= f.text_area :description, placeholder: "ルーム説明入力",autofocus: true, autocomplete: "description",class: "textarea" %></td>
      </tr>
      <tr>
        <th><%= f.label :料金, class: "label" %></th>
        <td> <%= f.text_field :price, placeholder: "１日あたりの料金を入力", autofocus: true, autocomplete: "price",class: "input" %></td>
      </tr>
		  <tr>
        <th><%= f.label :住所, class: "label" %></th>
        <td><%= f.text_field :address, placeholder: "住所入力", autofocus: true, autocomplete: "address",class: "input" %></td>
      </tr>
      <tr>
        <th><%= f.label :ルーム画像, class: "label" %></th>
        <td>
          <% if @room.img.attached? %>
            <%= image_tag @room.img ,class:"room-icon"%>
          <% end %>
          <%= f.file_field :img %>
        </td>
      </tr>
    </table>

    <div>
      <ul class="room-submit">
        <li><%= f.submit "登録" , id:"submit-btn"%></li>
		    <li ><%= link_to "部屋一覧に戻る", :rooms %></li>
      </ul>
    </div>
   <% end %>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="search">
<h2 class="kensaku">検索結果 :<span>
   <%= Room.where('name LIKE ? OR address LIKE ? OR description LIKE ?',"%#{params[:search]}%","%#{params[:search]}%","%#{params[:search]}%").count %>
</span>件</h2>

<div class="result">
  <% @rooms.each do |room| %>
  <ul class="result_display" >
    <li>
      <% if room.img.attached? %>
        <%= image_tag room.img ,class:"room-icon" %>
      <% end %>
    </li>
    <li id="name"><p><%= link_to room.name , room%></p></li>
    <li id="address"><p><%= room.address %></p></li>
    <li id="price"><p>¥<%= room.price %></p></li>
   </ul>
  <% end %>

</div>
</div>

app/views/rooms/show.html.erb
 <%= form_with model: @reservation, url: new_reservation_path, method: :get ,local: true do |r| %>
    <%= r.label :check_in_date ,"チェックイン" %><br>
    <%= r.date_field :check_in_date ,class:"reservation_day" %><br>
    <%= r.label :checkout_date ,"チェックアウト" %><br>
    <%= r.date_field :checkout_date ,class:"reservation_day" %><br>
  	<%= r.label :guests_count,"人数" %><br>
    <%= r.number_field :guests_count, min: 1 ,class:"reservation_num" %><br>
		<%= r.hidden_field :user_id, value: current_user.id %>
  	<%= r.hidden_field :room_id, value: @room.id %>
  <div class="show_reservation_btns">
    <ul >
      <li><%= r.submit "予約を確認する",id:"if_reserve_btn" %></li>
		  <li id="return_room_index_btn"><%= link_to "戻る", :rooms,id:"return_room_index" %></li>
    </ul>
  </div>
  <% end %>
</div>