config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  get 'homes/index'
  get 'top' => 'homes#top'

  root 'homes#top'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :users do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  resources :users do
    collection do
      get :profile
    end

    collection do
      get :show2
    end
  end

  resources :rooms do
    collection do
      get :search
    end
  end
  resources :reservations do
    collection do
      get :complete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="header">
    <div class="top">
      <div class="header_log">
        <div class="header-img">
         <a href= "/"><img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png" alt="ヘッダーのロゴ"></a>
        </div>
        
        <div class="search">
          <div class="area_search">
            <%= form_with url: search_rooms_path, method: :get, local: true do |s| %>
              <%= s.text_field :search,placeholder: "eria..." %>
              <%= s.submit :search, class: "btn"  %>
            <% end %>
          </div>
        
          <div class="keyword">
            <%= form_with url: search_rooms_path, method: :get, local: true do |s| %>
              <%= s.text_field :search,placeholder: "keyword..." %>
              <%= s.submit :search, class: "btn" %>
            <% end %>
          </div>
        </div>
      </div>

      <div class= "header_menu">
        <% if user_signed_in? %>
          <div class="hamburger">
            <span></span>
            <span></span>
            <span></span>
          </div>
          
          <nav class="globalMenuSp">
            <ul>
              <li><%= link_to "room登録", :new_room, class:"nonline" %></li>
              <li> <%= link_to "登録した部屋一覧", :rooms, class:"nonline" %></li>
              <li><%= link_to "予約済み一覧", :reservations, class:"nonline"  %></li>
              <li><%= link_to "myアカウント",  show2_users_path, class:"nonline" %></li></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nonline" %></li>
            </ul>
        <% else %>
        <ul class="unsign-menus">
          <li><%= link_to "ログイン", "/users/sign_in", class:"nonline login"  %></li>
          <li><%= link_to "新規登録", "/users/sign_up", class:"nonline new" %></li>
        </ul>
      </div>
      <% end %>
     <script>
       $(function() {
    $('.hamburger').click(function() {
        $(this).toggleClass('active');
 
        if ($(this).hasClass('active')) {
            $('.globalMenuSp').addClass('active');
        } else {
            $('.globalMenuSp').removeClass('active');
        }
    });
});
     </script>

    </header>
    <%if flash.notice%>
      <p class="notice"><%= notice %></p>
    <%end%>
    <%if flash.alert%>
      <p class="alert"><%= alert %></p>
    <%end%>
   </header>
   <%= yield %>

   <footer class="footer">
     <p class="footer_memo">© 2020 POTEPAN.INC.</p>
   </footer>
  </body>
</html>